st076569_12: managerlib.o st076569_12.o
	g++ managerlib.o st076569_12.o -o st076569_12 -lpthread

managerlib.o: 
	g++ -c ./source/managerlib.cpp -I ./headers

st076569_12.o:
	g++ -c ./source/st076569_12.cpp -I ./headers

clean:
	rm -f *.o

