st076569_1: stack.o st076569_1.o
	g++ stack.o st076569_1.o -o st076569_1

stack.o: 
	g++ -c ./source/stack.cpp -I ./headers

st076569_1.o:
	g++ -c ./source/st076569_1.cpp -I ./headers

clean:
	rm -f *.o

