st076569_2: raidlib.o st076569_2.o
	g++ raidlib.o st076569_2.o -o st076569_2

raidlib.o: 
	g++ -c ./source/raidlib.cpp -I ./headers

st076569_2.o:
	g++ -c ./source/st076569_2.cpp -I ./headers

clean:
	rm -f *.o

