st076569_6: iolib.o st076569_6.o
	g++ iolib.o st076569_6.o -o st076569_6

iolib.o: 
	g++ -c ./source/iolib.cpp -I ./headers

st076569_6.o:
	g++ -c ./source/st076569_6.cpp -I ./headers

clean:
	rm -f *.o

