st076569_7: functions.o st076569_7.o
	g++ functions.o st076569_7.o -o st076569_7

functions.o: 
	g++ -c ./source/functions.cpp -I ./headers

st076569_7.o:
	g++ -c ./source/st076569_7.cpp -I ./headers
clean:
	rm -f st076569_7 *.o

