st076569_2: functions.o st076569_2.o
	g++ functions.o st076569_2.o -o st076569_2

functions.o: 
	g++ -c ./source/functions.cpp -I ./headers

st076569_2.o:
	g++ -c ./source/st076569_2.cpp -I ./headers

clean:
	rm -f *.o
