st076569_3: queuelib.o st076569_3.o
	g++ queuelib.o st076569_3.o -o st076569_3

queuelib.o: 
	g++ -c ./source/queuelib.cpp -I ./headers

st076569_3.o:
	g++ -c ./source/st076569_3.cpp -I ./headers

clean:
	rm -f *.o

