st076569_5: functions.o st076569_5.o
	g++ functions.o st076569_5.o -o st076569_5

functions.o: 
	g++ -c ./source/functions.cpp -I ./headers

st076569_5.o:
	g++ -c ./source/st076569_5.cpp -I ./headers

clean:
	rm -f *.o

