st076569_5: swaplib.o st076569_5.o
	g++ swaplib.o st076569_5.o -o st076569_5

swaplib.o: 
	g++ -c ./source/swaplib.cpp -I ./headers

st076569_5.o:
	g++ -c ./source/st076569_5.cpp -I ./headers

clean:
	rm -f *.o

